/**
 * Build the self-contained browser demo.
 *
 * The demo must not reimplement verification. It bundles `packages/core`
 * itself, so whatever the page does is what the library does; a divergence
 * between the demo and the specification is not possible by construction.
 * Everything is inlined into one HTML file with no external requests, which is
 * also what lets it verify with the network unplugged — the property
 * Section 4 of the paper claims and a test already asserts.
 *
 * The signing keys used here are the suite's published test keys. Their private
 * halves are in this repository and protect nothing. That is stated on the page
 * itself, because a demo that verifies and looks authoritative is precisely the
 * artefact this project warns about.
 */

import { execFileSync } from 'node:child_process';
import { mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { signProfileA2 } from '../packages/core/dist/profileA2.js';
import { keyPairFromScalar } from './keys.ts';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DEMO = join(ROOT, 'demo');
const TMP = join(DEMO, '.build');

interface Suite {
  keys: Record<string, { scalar: string }>;
  pinned: unknown;
  trustLists: Record<string, unknown>;
  timestamps: Record<string, unknown>;
  time: { issuedAt: number; expiresAt: number; nowValid: number };
  cases: readonly {
    id: string;
    profile: string;
    type: string;
    description: string;
    input: Record<string, unknown>;
    state: Record<string, unknown>;
    expect: string;
    reason: string | null;
  }[];
}

const suite = JSON.parse(readFileSync(join(ROOT, 'vectors', 'vectors.json'), 'utf8')) as Suite;

/* ------------------------------------------------------------------ *
 * 1. Bundle the real library for the browser
 * ------------------------------------------------------------------ */

mkdirSync(TMP, { recursive: true });
writeFileSync(
  join(TMP, 'entry.ts'),
  [
    '// Generated by tools/build-demo.ts. Re-exports the real verification path.',
    "export { TrustAnchor, verifyProfileA, verifyProfileA2, verifyProfileB, KhSqrError,",
    "  stripCrc, appendCrc, crc16CcittFalse } from '../../packages/core/dist/index.js';",
  ].join('\n'),
);

const esbuild = join(ROOT, 'node_modules', '.pnpm', 'node_modules', '.bin', 'esbuild');
execFileSync(esbuild, [
  join(TMP, 'entry.ts'),
  '--bundle',
  '--format=iife',
  '--global-name=KHSQR',
  '--platform=browser',
  '--target=es2022',
  '--minify',
  `--outfile=${join(TMP, 'khsqr.js')}`,
]);
const bundle = readFileSync(join(TMP, 'khsqr.js'), 'utf8');

/* ------------------------------------------------------------------ *
 * 2. The currency-substitution pair
 * ------------------------------------------------------------------ *
 *
 * Two codes from the same payee for the same number, differing only in tag 53.
 * BOTH are genuinely signed and both verify. This is P9, and it is the case a
 * live demo makes in a way prose cannot: the reader watches two valid
 * signatures and sees that validity was never the question.
 */

const key = await keyPairFromScalar(suite.keys['issuer']!.scalar);
const { issuedAt, expiresAt } = suite.time;

const payeeCode = (currencyNumeric: string): string =>
  '00020101021230310011abaakhppxxx0112855012345678520458125303' +
  currencyNumeric +
  '540472005802KH5908SOK DARA6010PHNOM PENH';

async function sign(currencyNumeric: string): Promise<string> {
  const signed = await signProfileA2({
    payload: payeeCode(currencyNumeric),
    privateKey: key.privateKey,
    kid: key.kid,
    issuedAt,
    expiresAt,
    payeeClass: 'M',
  });
  return signed.payload;
}

const khr = await sign('116');
const usd = await sign('840');

/* ------------------------------------------------------------------ *
 * 3. Curate the cases the page offers
 * ------------------------------------------------------------------ */

const pick = (id: string) => {
  const found = suite.cases.find((c) => c.id === id);
  if (found === undefined) throw new Error(`vector ${id} not found — the demo would ship a lie`);
  return found;
};

const anchorState = pick('A2-accept-dynamic').state;

const scenarios = [
  {
    id: 'genuine',
    label: 'A genuine signed payment code',
    teaches: 'It verifies. That is all it tells you.',
    payload: khr,
    encodingVersion: 2,
    state: anchorState,
  },
  {
    id: 'currency',
    label: 'The same payee, the same number, a different currency',
    teaches:
      'Also genuine, also verifies. 7,200 riel and 7,200 dollars differ by a factor of about four thousand, and three characters carry the whole loss.',
    payload: usd,
    encodingVersion: 2,
    state: anchorState,
  },
  {
    id: 'tampered',
    label: 'One character of the merchant name changed',
    teaches: 'Rejected. Forgery of the instrument is what a signature closes.',
    payload: null,
    derive: 'tamper-name',
    encodingVersion: 2,
    state: anchorState,
  },
  {
    id: 'appended',
    label: 'Data appended after the signature',
    teaches:
      'Rejected. The signed region is a prefix, so an attacker cannot extend the payload and leave the signed bytes intact.',
    payload: pick('A2-reject-appended-after-signature').input['payload'] as string,
    encodingVersion: 2,
    state: pick('A2-reject-appended-after-signature').state,
  },
  {
    id: 'unknown-kid',
    label: 'Signed by a key that is not on the trust list',
    teaches: 'Rejected. A signature is only as good as the list the verifier trusts.',
    payload: pick('A-reject-unknown-kid').input['payload'] as string,
    encodingVersion: 1,
    state: pick('A-reject-unknown-kid').state,
  },
  {
    id: 'revoked',
    label: 'Signed by a revoked key',
    teaches: 'Rejected. Revocation invalidates everything that key ever signed.',
    payload: pick('A-reject-revoked-key').input['payload'] as string,
    encodingVersion: 1,
    state: pick('A-reject-revoked-key').state,
  },
  {
    id: 'expired',
    label: 'A dynamic code past its expiry',
    teaches: 'Rejected. A one-transaction code is not reusable.',
    payload: pick('A-reject-expired-dynamic').input['payload'] as string,
    encodingVersion: 1,
    state: pick('A-reject-expired-dynamic').state,
  },
  {
    id: 'stale-trustlist',
    label: 'The trust list is too old',
    teaches:
      'Rejected — and note what failed. The code is fine; the verifier stopped trusting its own list. Silence from the trust infrastructure is treated as hostile.',
    payload: pick('A-reject-trustlist-stale').input['payload'] as string,
    encodingVersion: 1,
    state: pick('A-reject-trustlist-stale').state,
  },
];

const verifiable = suite.cases.filter((c) => c.type === 'verify');

const data = {
  generated: new Date().toISOString().slice(0, 10),
  pinned: suite.pinned,
  trustLists: suite.trustLists,
  timestamps: suite.timestamps,
  scenarios,
  suite: verifiable.map((c) => ({
    id: c.id,
    profile: c.profile,
    expect: c.expect,
    reason: c.reason,
    encodingVersion: c.input['encodingVersion'] ?? 1,
    payload: c.input['payload'],
    state: c.state,
  })),
  counts: {
    total: verifiable.length,
    negative: verifiable.filter((c) => c.expect === 'reject').length,
  },
};

/* ------------------------------------------------------------------ *
 * 4. Inline everything into the page
 * ------------------------------------------------------------------ */

const template = readFileSync(join(DEMO, 'template.html'), 'utf8');
const page = template
  .replace('/*__KHSQR_BUNDLE__*/', () => bundle)
  .replace('/*__DEMO_DATA__*/', () => JSON.stringify(data))
  .replace('/*__BUILD_DATE__*/', data.generated);

if (page.includes('__KHSQR_BUNDLE__') || page.includes('__DEMO_DATA__') || page.includes('__BUILD_DATE__')) {
  throw new Error('a placeholder survived substitution');
}

writeFileSync(join(DEMO, 'qrseal-demo.html'), page);
rmSync(TMP, { recursive: true, force: true });

process.stdout.write(
  `wrote demo/qrseal-demo.html\n` +
    `  ${(page.length / 1024).toFixed(0)} KB, no external requests\n` +
    `  ${scenarios.length} scenarios, ${data.counts.total} suite cases (${data.counts.negative} negative)\n`,
);
