/**
 * Measure the QR symbol each payload actually needs.
 *
 * Symbol size is the whole practical cost of signing a payment code: a
 * merchant with a printed sticker has to reprint it, and a larger symbol needs
 * more physical area for the same module size, or the same area with smaller
 * modules and a worse scan rate on a cheap phone in poor light. The table in
 * README.md is generated by this script rather than transcribed.
 *
 * The encoding mode is reported alongside the version because it dominates
 * everything else: QR alphanumeric mode packs two characters into 11 bits,
 * byte mode uses 8 bits per character. A single lowercase letter anywhere in
 * the payload forces byte mode for that segment and costs roughly 45 per cent
 * more capacity.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import QRCode from 'qrcode';

const ROOT = dirname(fileURLToPath(import.meta.url)) + '/..';

interface Measurement {
  readonly label: string;
  readonly characters: number;
  readonly version: number;
  readonly modules: number;
  readonly mode: string;
  readonly note: string;
}

const ALPHANUMERIC = /^[0-9A-Z $%*+\-./:]*$/;

function measure(label: string, payload: string, note = ''): Measurement {
  const symbol = QRCode.create(payload, { errorCorrectionLevel: 'M' });
  const segments = symbol.segments.map((s) => s.mode.id as string);
  return {
    label,
    characters: payload.length,
    version: symbol.version,
    modules: symbol.modules.size,
    mode: [...new Set(segments)].join('+'),
    note,
  };
}

interface Suite {
  readonly cases: readonly { id: string; input: Record<string, unknown> }[];
}

const suite = JSON.parse(readFileSync(join(ROOT, 'vectors', 'vectors.json'), 'utf8')) as Suite;
const payloadOf = (id: string): string =>
  suite.cases.find((c) => c.id === id)?.input['payload'] as string;

/** The same merchant payload with no signature template: the pre-KH-SQR baseline. */
const UNSIGNED = '00020101021230310011abaakhppxxx01128550123456785204581253031165405250005802KH5908SOK DARA6010PHNOM PENH63048620';

const profileA = payloadOf('A-accept-published-reference');
const profileA2 = payloadOf('A2-accept-dynamic');
const profileB = payloadOf('B-accept-published-reference');

const measurements: Measurement[] = [
  measure('Unsigned KHQR baseline', UNSIGNED),
  measure('Profile A signed, encoding v1', profileA, 'not walkable by a strict EMVCo parser'),
  measure('Profile A signed, encoding v2', profileA2, 'EMVCo two-digit lengths throughout'),
  measure('Profile B credential', profileB),
];

/**
 * The reference payloads carry a lowercase acquirer identifier
 * (`abaakhppxxx`), which forces a byte-mode segment and enlarges the symbol.
 * Measuring an uppercase variant separates the cost of the signature from the
 * cost of that one field, which is a deployment choice an issuer can make.
 */
const upperUnsigned = UNSIGNED.replace('abaakhppxxx', 'ABAAKHPPXXX');
const upperA = profileA.replace('abaakhppxxx', 'ABAAKHPPXXX');
const upperA2 = profileA2.replace('abaakhppxxx', 'ABAAKHPPXXX');

const variants: Measurement[] = [
  measure('Unsigned baseline, uppercase acquirer id', upperUnsigned, 'alphanumeric mode throughout'),
  measure('Profile A v1, uppercase acquirer id', upperA, 'alphanumeric mode throughout'),
  measure('Profile A v2, uppercase acquirer id', upperA2, 'alphanumeric mode throughout'),
];

const allAlphanumeric = (payload: string): boolean => ALPHANUMERIC.test(payload);

const rows = [...measurements, ...variants];
const width = Math.max(...rows.map((r) => r.label.length));

process.stdout.write('QR symbol measurements, error-correction level M\n\n');
process.stdout.write(
  `${'Payload'.padEnd(width)}  Chars  Version  Modules  Mode\n${'-'.repeat(width)}  -----  -------  -------  ----\n`,
);
for (const row of rows) {
  process.stdout.write(
    `${row.label.padEnd(width)}  ${String(row.characters).padStart(5)}  ` +
      `${String(row.version).padStart(7)}  ${`${row.modules} x ${row.modules}`.padStart(7)}  ${row.mode}\n`,
  );
}

process.stdout.write(
  `\nreference payloads are fully alphanumeric: A=${allAlphanumeric(profileA)}, B=${allAlphanumeric(profileB)}\n`,
);

writeFileSync(
  join(ROOT, 'docs', 'qr-measurements.json'),
  `${JSON.stringify(
    {
      generatedBy: 'tools/measure-qr.ts',
      errorCorrectionLevel: 'M',
      library: 'qrcode (node), ISO/IEC 18004 capacity tables',
      measurements: rows,
    },
    null,
    2,
  )}\n`,
);
